[package]
name = "bandname"
version = "0.1.0"
authors = ["Finnkauski <iwiivi@gmail.com>"]
edition = "2018"

[dependencies]
rocket = "*"
serde = "*"
serde_derive = "1.0"
diesel = {version = "*", features = ["postgress", "r2d2"]}
diesel_migrations = "*"
cute = "*"

[dependencies.rocket_contrib]
version = "0.4.1"
default-features = false
features = ["diesel_postgres_pool", "tera_templates", "serve"]
